/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import model.SinhvienATTT;
import model.SinhvienMatMa;

/**
 *
 * @author zung
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_masv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_hoten = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_ngaysinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_diemtb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_hocphi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_donvi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_luong = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        rb_svat = new javax.swing.JRadioButton();
        rb_svmm = new javax.swing.JRadioButton();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        cbox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sinh viên");

        jLabel2.setText("Mã sinhvien");

        jLabel3.setText("Họ tên");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Giới tính");

        jLabel6.setText("Điểm trung bình");

        jLabel7.setText("Học phí");

        jLabel8.setText("Đơn vị");

        jLabel9.setText("Lương");

        btn_save.setText("Lưu");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_svat);
        rb_svat.setText("Sinh viên ATTT");
        rb_svat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_svatActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_svmm);
        rb_svmm.setText("Sinh viên mật mã");
        rb_svmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_svmmActionPerformed(evt);
            }
        });

        buttonGroup2.add(nam);
        nam.setText("Nam");

        buttonGroup2.add(nu);
        nu.setText("Nu");

        cbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(33, 33, 33)))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_svat)
                                .addGap(32, 32, 32)
                                .addComponent(rb_svmm))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_diemtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_hocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tf_luong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_donvi, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nam)
                                .addGap(115, 115, 115)
                                .addComponent(nu)))
                        .addGap(0, 159, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tf_diemtb, tf_donvi, tf_hocphi, tf_hoten, tf_masv, tf_ngaysinh});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rb_svat)
                    .addComponent(rb_svmm))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nam)
                    .addComponent(nu))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_diemtb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tf_hocphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_donvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(134, 134, 134))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String masv =tf_masv.getText();
        String hoten =tf_hoten.getText();
        String ngaysinh =tf_ngaysinh.getText();
        String gioitinh= nam.isSelected() ?"nam":"nu";
        String diemtb =tf_diemtb.getText();
        String hocphi =tf_hocphi.getText();
        String donvi =tf_donvi.getText();
        String luong =tf_luong.getText();
        
        if(rb_svat.isSelected()){
            if(masv.equals("")||hoten.equals("")||ngaysinh.equals("")||(!nam.isSelected()&&!nu.isSelected())||diemtb.equals("")||hocphi.equals("")){
                JOptionPane.showMessageDialog(null, "nhap thieu thong tin");
                return;
            }
            else{
                try {
                    try {
                     float diem =Float.parseFloat(diemtb);
                     float hp =Float.parseFloat(hocphi);
                     FileWriter fw=new FileWriter("sinhvien.dat",true);
                     BufferedWriter bw =new BufferedWriter(fw);
                     SinhvienATTT svat =new SinhvienATTT(masv, hoten, ngaysinh, gioitinh, diem, hp);
                     bw.append(masv+"$"+ hoten+"$"+ ngaysinh+"$"+ gioitinh+"$"+ diem+"$"+ hp);
                     bw.newLine();
                     bw.close();
                     fw.close();
                     JOptionPane.showMessageDialog(null, "luu file svat thanh cong");
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "nhap sai dinh dang");
                }
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, "luu file that bai");
                }
                
               
            }
        }
        else if(rb_svmm.isSelected()){
             if(masv.equals("")||hoten.equals("")||ngaysinh.equals("")||(!nam.isSelected()&&!nu.isSelected())||diemtb.equals("")||donvi.equals("")||luong.equals("")){
                JOptionPane.showMessageDialog(null, "nhap thieu thong tin");
                return;
            }
            else{
                try {
                    try {
                    
                     float salary =Float.parseFloat(luong);
                     FileWriter fw=new FileWriter("svmm.dat",true);
                     BufferedWriter bw =new BufferedWriter(fw);
                     SinhvienMatMa svmm =new SinhvienMatMa(masv, hoten, ngaysinh, gioitinh, salary, donvi, salary);
                     bw.append(masv+"$"+hoten+"$"+ngaysinh+"$"+gioitinh+"$"+salary+"$"+donvi+"$"+salary);
                     bw.newLine();
                     bw.close();
                     fw.close();
                     JOptionPane.showMessageDialog(null, "luu file svmm thanh cong");
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "nhap sai dinh dang");
                }
                } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, "luu file that bai");
                }
                
               
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "chua chon loai sinh vien");
            return;
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void rb_svatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_svatActionPerformed
      
       tf_hocphi.setEnabled(true);
       tf_donvi.setEnabled(false);
       tf_luong.setEnabled(false);
    }//GEN-LAST:event_rb_svatActionPerformed

    private void rb_svmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_svmmActionPerformed
         tf_hocphi.setEnabled(false);
       tf_donvi.setEnabled(true);
       tf_luong.setEnabled(true);
    }//GEN-LAST:event_rb_svmmActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
       buttonGroup1.clearSelection();
       buttonGroup2.clearSelection();
       tf_masv.setText("");
       tf_hoten.setText("");
       tf_ngaysinh.setText("");
       tf_diemtb.setText("");
       tf_hocphi.setText("");
       tf_donvi.setText("");
       tf_luong.setText("");
         tf_hocphi.setEnabled(true);
       tf_donvi.setEnabled(true);
       tf_luong.setEnabled(true);
       String op =cbox.getItemAt(cbox.getSelectedIndex())+"";
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton nam;
    private javax.swing.JRadioButton nu;
    private javax.swing.JRadioButton rb_svat;
    private javax.swing.JRadioButton rb_svmm;
    private javax.swing.JTextField tf_diemtb;
    private javax.swing.JTextField tf_donvi;
    private javax.swing.JTextField tf_hocphi;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_luong;
    private javax.swing.JTextField tf_masv;
    private javax.swing.JTextField tf_ngaysinh;
    // End of variables declaration//GEN-END:variables
}
