/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import model.word;

/**
 *
 * @author zung
 */
public class Dictionary extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    ArrayList<word> list_word;

    public Dictionary() {
        initComponents();
        list_begin();
        printListbegin();
        sapXepList();
        System.out.println("----------");
        printListbegin();

    }

    public void list_begin() {
        list_word = new ArrayList<>();
        word w1 = new word(1, "one", "mot");
        word w2 = new word(2, "two", "hai");
        word w3 = new word(3, "three", "ba");
        word w4 = new word(4, "four", "bon");
        word w5 = new word(5, "five", "nam");
        word w6 = new word(6, "six", "sau");
        word w7 = new word(7, "seven", "bay");
        word w8 = new word(8, "eight", "tam");
        list_word.add(w1);
        list_word.add(w2);
        list_word.add(w3);
        list_word.add(w4);
        list_word.add(w5);
        list_word.add(w6);
        list_word.add(w7);
        list_word.add(w8);

    }

    public void printListbegin() {
        for (word wo : list_word) {
            wo.showinfor();
        }
    }

    public void sapXepList() {
        Collections.sort(list_word, new Comparator<word>() {

            @Override
            public int compare(word w1, word w2) {
                return w1.getEn().compareTo(w2.getEn());
            }
        });
    }

    public int binaryFind(String value) {
        int left = 0, right = list_word.size()-1, mid;
        int kq = -1;
        while (left < right) {
            mid = (left + right) / 2;
            word wmid = list_word.get(mid);

            if (wmid.getEn().equals(value)) {
                kq = mid;
                break;
            } else if (wmid.getEn().compareTo(value) > 0) {
                right = mid;
            } else  {
                left = mid + 1;
            }
        }
        return kq;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_eng = new javax.swing.JTextField();
        tf_vne = new javax.swing.JTextField();
        btn_find = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("English");

        jLabel2.setText("Vietnam");

        btn_find.setText("Find");
        btn_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findActionPerformed(evt);
            }
        });

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_find, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_vne, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(tf_eng))))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_eng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_vne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_find)
                    .addComponent(btn_add))
                .addContainerGap(423, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findActionPerformed
        
      if(!tf_eng.getText().equals("")){
          int kq= binaryFind(tf_eng.getText());
          if(kq==-1){
              JOptionPane.showMessageDialog(null,"tu nay chua co trong tu dien moi ban bo sun");
          }
          else{
              tf_vne.setText(list_word.get(kq).getVn());
          }
      }
      else{
          JOptionPane.showMessageDialog(null, "ban chua nhap tu english");
      }
    }//GEN-LAST:event_btn_findActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (!tf_eng.getText().equals("") && !tf_vne.getText().equals("")) {
            int kq = binaryFind(tf_eng.getText());
            if (kq == -1) {
                word w = new word(list_word.size() + 1, tf_eng.getText(), tf_vne.getText());
                list_word.add(w);
                sapXepList();
                JOptionPane.showMessageDialog(null, "them thanh cong");

            } else {
                JOptionPane.showInternalMessageDialog(null, "tu nay da co trong tu dien");
            }

        } else {
            JOptionPane.showInternalMessageDialog(null, "chua nhap du thong tin");
        }

    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tf_eng;
    private javax.swing.JTextField tf_vne;
    // End of variables declaration//GEN-END:variables
}
