/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FileIO;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.BookManager;
import model.Reader;

/**
 *
 * @author zung
 */
public class MainFrame extends javax.swing.JFrame {

    private static final String File_Book = "SACH.TXT";
    private static final String File_READER = "BD.TXT";
    private static final String File_BOOKMANAGER = "QLMS.TXT";
    DefaultTableModel tableBook;
    DefaultTableModel tableReader;
    DefaultTableModel tableBookManager;

    ArrayList<Book> listbook; // tao 1 mang doi tuong sach[id,tensach,tacgia,...]
    ArrayList<Reader> listReader; //tao 1 mang nguoi doc
    ArrayList<BookManager> listBookManager;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý mượn sách");
        tableBook = (DefaultTableModel) table1.getModel();
        tableReader = (DefaultTableModel) table2.getModel();
        tableBookManager = (DefaultTableModel) table3.getModel();
        loadDataToTable();
        loadIdToCbox();

    }

    public void loadIdToCbox() {
        cbox2.removeAllItems();
        cbox3.removeAllItems();
        for (Book book : listbook) {
            cbox2.addItem(book.getId() + "");
        }
        for (Reader reader : listReader) {
            cbox3.addItem(reader.getId() + "");
        }
    }

    public void loadDataToTable() {
        listbook = new ArrayList<>();
        listReader = new ArrayList<>();  // neu khong khoi tao thi no se tra ve null
        listBookManager =new ArrayList<>();
        FileIO.readFromFile(listbook, File_Book); // doc du lieu tu file sach.txt 
        FileIO.readFromFile(listReader, File_READER);//doc du lieu tu file bd.txt
        FileIO.readFromFile(listBookManager, File_BOOKMANAGER);
        for (Book b : listbook) {
            tableBook.addRow(b.toObject());
        }
        for (Reader r : listReader) {
            tableReader.addRow(r.toObject());
        }
        for (BookManager bm : listBookManager) {
            tableBookManager.addRow(bm.toObject());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_readername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_readeraddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_readerphone = new javax.swing.JTextField();
        btn_Add2 = new javax.swing.JButton();
        btn_Save2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tf_soluongmuon = new javax.swing.JTextField();
        btn_Add3 = new javax.swing.JButton();
        btn_Save3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        cbox4 = new javax.swing.JComboBox<>();
        tf_tenbd = new javax.swing.JTextField();
        tf_tensach = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_bookname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_bookauthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_bookyear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_bookamount = new javax.swing.JTextField();
        cbox_bookmajor = new javax.swing.JComboBox<>();
        btn_Add1 = new javax.swing.JButton();
        btn_Save1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Họ tên");

        jLabel7.setText("Địa chỉ");

        tf_readeraddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_readeraddressActionPerformed(evt);
            }
        });

        jLabel8.setText("Số điện thoại");

        tf_readerphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_readerphoneActionPerformed(evt);
            }
        });

        btn_Add2.setText("Thêm");
        btn_Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add2ActionPerformed(evt);
            }
        });

        btn_Save2.setText("Lưu vào file");
        btn_Save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save2ActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bạn đọc", "Họ tên", "Địa chỉ", "Số điện thoại"
            }
        ));
        jScrollPane2.setViewportView(table2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_readername)
                    .addComponent(tf_readeraddress)
                    .addComponent(btn_Add2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Save2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_readerphone)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tf_readername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_readeraddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_readerphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Add2)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Save2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 40, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        table.addTab("Bạn đọc", jPanel2);

        jLabel9.setText("Chọn đầu sách:");

        jLabel10.setText("Chọn mã bạn đọc:");

        jLabel11.setText("Số lượng");

        btn_Add3.setText("Thêm");
        btn_Add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add3ActionPerformed(evt);
            }
        });

        btn_Save3.setText("Lưu vào File");
        btn_Save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save3ActionPerformed(evt);
            }
        });

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Mã bạn đọc", "Tên bạn đọc", "Số lượng mượn"
            }
        ));
        jScrollPane3.setViewportView(table3);

        cbox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sắp xếp theo tên BD", "sắp xếp theo sl sách" }));
        cbox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox4ActionPerformed(evt);
            }
        });

        tf_tenbd.setText("Nhập tên bạn...");
        tf_tenbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tenbdActionPerformed(evt);
            }
        });

        tf_tensach.setText("Nhập tên sách...");

        btn_search.setText("Tìm Kiếm");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_tensach)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(cbox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_soluongmuon)
                        .addComponent(btn_Add3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Save3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(cbox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_tenbd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(cbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(cbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(tf_soluongmuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_Add3)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Save3)
                        .addGap(32, 32, 32)
                        .addComponent(cbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_tenbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tf_tensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_search)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        table.addTab("Quản Lý Mượn Sách", jPanel3);

        jLabel1.setText("Sách");

        jLabel2.setText("Tác giả");

        tf_bookauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookauthorActionPerformed(evt);
            }
        });

        jLabel3.setText("Chuyên ngành");

        tf_bookyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookyearActionPerformed(evt);
            }
        });

        jLabel4.setText("Năm xuất bản");

        jLabel5.setText("Số lượng");

        tf_bookamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bookamountActionPerformed(evt);
            }
        });

        cbox_bookmajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Add1.setText("Thêm");
        btn_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add1ActionPerformed(evt);
            }
        });

        btn_Save1.setText("Lưu vào file");
        btn_Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Save1ActionPerformed(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tên sách", "Tác giả", "Chuyên ngành", "Năm xuất bản", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(4).setHeaderValue("Năm xuất bản");
            table1.getColumnModel().getColumn(5).setHeaderValue("Số lượng");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(tf_bookname)
                    .addComponent(jLabel2)
                    .addComponent(tf_bookauthor, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(tf_bookyear, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tf_bookamount, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(cbox_bookmajor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Save1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_bookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_bookauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbox_bookmajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tf_bookyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_bookamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Add1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Save1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        table.addTab("Sách", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(table)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(table)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_bookauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookauthorActionPerformed

    private void tf_bookyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookyearActionPerformed

    private void tf_bookamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bookamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bookamountActionPerformed

    private void btn_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add1ActionPerformed
        String bookName = tf_bookname.getText();
        String bookAuthor = tf_bookauthor.getText();
        String bookMajor = cbox_bookmajor.getItemAt(cbox_bookmajor.getSelectedIndex());
        String bookYear = tf_bookyear.getText();
        String bookAmount = tf_bookamount.getText();

        if (bookName.equals("") || bookAuthor.equals("") || bookMajor.equals("")
                || bookYear.equals("") || bookAmount.equals("")) {
            JOptionPane.showMessageDialog(null, "ban da nhap thieu thong tin ");
            return;
        }
        try {
            int amount = Integer.parseInt(bookAmount);
            int pos = listbook.size() - 1;
            if (pos != -1) {
                Book.setCurrent_id(listbook.get(pos).getId() + 1);
            }
            Book book = new Book(bookName, bookAuthor, bookMajor, bookYear, amount);
            for (int i = 0; i < listbook.size(); i++) {
                if (listbook.get(i).equals(book)) {
                    JOptionPane.showMessageDialog(null, "trung dau sach");
                    return;
                }
            }
            tableBook.addRow(book.toObject());
            listbook.add(book);
            loadIdToCbox();

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_btn_Add1ActionPerformed

    private void tf_readeraddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_readeraddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_readeraddressActionPerformed

    private void tf_readerphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_readerphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_readerphoneActionPerformed

    private void btn_Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add2ActionPerformed
        String readerName = tf_readername.getText();
        String readerAddress = tf_readeraddress.getText();
        String readerPhone = tf_readerphone.getText();
        if (readerName.equals("") || readerAddress.equals("") || readerPhone.equals("")) {
            JOptionPane.showMessageDialog(null, "ban da nhap thieu thong tin");
            return;
        }
        int position = listReader.size() - 1;
        if (position != -1) {
            Reader.setCurrent_id(listReader.get(position).getId() + 1);
        }
        if (readerPhone.length() <= 9 || readerPhone.length() > 10 || !readerPhone.startsWith("0")) {
            JOptionPane.showMessageDialog(null, "so dien thoai khong hop le");
            return;
        }
        Reader reader = new Reader(readerName, readerAddress, readerPhone);
        for (int i = 0; i < listReader.size(); i++) {
            if (listReader.get(i).equals(reader)) {
                JOptionPane.showMessageDialog(null, "nhap trung thong tin");
                return;
            }
        }
        tableReader.addRow(reader.toObject());
        listReader.add(reader);
        loadIdToCbox();
    }//GEN-LAST:event_btn_Add2ActionPerformed

    private void btn_Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save1ActionPerformed
        FileIO.writeToFile(listbook, File_Book);
        JOptionPane.showMessageDialog(null, " File is Save");
    }//GEN-LAST:event_btn_Save1ActionPerformed

    private void btn_Save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save2ActionPerformed
        FileIO.writeToFile(listReader, File_READER);
        JOptionPane.showMessageDialog(null, " File is Save");

    }//GEN-LAST:event_btn_Save2ActionPerformed

    private void btn_Add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add3ActionPerformed
        int bookIndex = cbox2.getSelectedIndex();
        int readerIndex = cbox3.getSelectedIndex();
        String amount =tf_soluongmuon.getText();
        try {
            int a = Integer.parseInt(amount);
            Book b = listbook.get(bookIndex);
            Reader r = listReader.get(readerIndex);
            BookManager bm = new BookManager(b, r, a);
            for (int i=0 ;i<listBookManager.size();i++) {
                if(listBookManager.get(i).equals(bm)){
                    JOptionPane.showMessageDialog(null, "nhap trung thong tin" );
                    return;
                }
            }
            tableBookManager.addRow(bm.toObject());
            listBookManager.add(bm);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "nhap sai dinh dang");
        }

    }//GEN-LAST:event_btn_Add3ActionPerformed

    private void btn_Save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Save3ActionPerformed
          FileIO.writeToFile(listBookManager, File_BOOKMANAGER);
        JOptionPane.showMessageDialog(null, " File is Save");
    }//GEN-LAST:event_btn_Save3ActionPerformed

    private void cbox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox4ActionPerformed
       String option =cbox4.getItemAt(cbox4.getSelectedIndex());
       if(option.equals("sắp xếp theo tên BD")){
           Comparator<BookManager> cpt =(BookManager o1, BookManager o2) -> {
               String bookName1 =o1.getReader().getName();
               String bookName2 =o2.getReader().getName();
               return bookName1.compareTo(bookName2);
           };
           Collections.sort(listBookManager,cpt );
       }
       else{
           Collections.sort(listBookManager,Comparator.comparing(BookManager::getAmount).reversed());
       }
        tableBookManager.setRowCount(0);
        for (BookManager bm : listBookManager) {
            tableBookManager.addRow(bm.toObject());
        }
        
    }//GEN-LAST:event_cbox4ActionPerformed

    private void tf_tenbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tenbdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tenbdActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
       String book_name =tf_tensach.getText();
       String reader_name =tf_tenbd.getText();
        if (book_name.equals("")&& reader_name.equals("")) {
            JOptionPane.showMessageDialog(null, "nhap thieu thong tin");
            return;
        }
        tableBookManager.setRowCount(0);
        for (BookManager bm : listBookManager) {
            if(bm.getBook().getBookName().contains(book_name)
                    && bm.getReader().getName().contains(reader_name)){
                tableBookManager.addRow(bm.toObject());
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Add1;
    private javax.swing.JButton btn_Add2;
    private javax.swing.JButton btn_Add3;
    private javax.swing.JButton btn_Save1;
    private javax.swing.JButton btn_Save2;
    private javax.swing.JButton btn_Save3;
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> cbox2;
    private javax.swing.JComboBox<String> cbox3;
    private javax.swing.JComboBox<String> cbox4;
    private javax.swing.JComboBox<String> cbox_bookmajor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTextField tf_bookamount;
    private javax.swing.JTextField tf_bookauthor;
    private javax.swing.JTextField tf_bookname;
    private javax.swing.JTextField tf_bookyear;
    private javax.swing.JTextField tf_readeraddress;
    private javax.swing.JTextField tf_readername;
    private javax.swing.JTextField tf_readerphone;
    private javax.swing.JTextField tf_soluongmuon;
    private javax.swing.JTextField tf_tenbd;
    private javax.swing.JTextField tf_tensach;
    // End of variables declaration//GEN-END:variables
}
